"""Initial models

Revision ID: 6f18ab5362ff
Revises:
Create Date: 2026-07-09 23:28:46.703788

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f18ab5362ff"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fetch_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("league", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fetch_runs_league"), "fetch_runs", ["league"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("league", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_id"), "teams", ["id"], unique=False)
    op.create_index(op.f("ix_teams_league"), "teams", ["league"], unique=False)
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("league", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_games_away_team_id"), "games", ["away_team_id"], unique=False)
    op.create_index(op.f("ix_games_date"), "games", ["date"], unique=False)
    op.create_index(op.f("ix_games_home_team_id"), "games", ["home_team_id"], unique=False)
    op.create_index(op.f("ix_games_id"), "games", ["id"], unique=False)
    op.create_index(op.f("ix_games_league"), "games", ["league"], unique=False)
    op.create_table(
        "ratings",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("elo_rating", sa.Float(), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("team_id"),
    )
    op.create_table(
        "predictions",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("home_win_prob", sa.Float(), nullable=False),
        sa.Column("away_win_prob", sa.Float(), nullable=False),
        sa.Column("draw_prob", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_table(
        "rating_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=True),
        sa.Column("elo_rating", sa.Float(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rating_history_date"), "rating_history", ["date"], unique=False)
    op.create_index(op.f("ix_rating_history_game_id"), "rating_history", ["game_id"], unique=False)
    op.create_index(op.f("ix_rating_history_team_id"), "rating_history", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rating_history_team_id"), table_name="rating_history")
    op.drop_index(op.f("ix_rating_history_game_id"), table_name="rating_history")
    op.drop_index(op.f("ix_rating_history_date"), table_name="rating_history")
    op.drop_table("rating_history")
    op.drop_table("predictions")
    op.drop_table("ratings")
    op.drop_index(op.f("ix_games_league"), table_name="games")
    op.drop_index(op.f("ix_games_id"), table_name="games")
    op.drop_index(op.f("ix_games_home_team_id"), table_name="games")
    op.drop_index(op.f("ix_games_date"), table_name="games")
    op.drop_index(op.f("ix_games_away_team_id"), table_name="games")
    op.drop_table("games")
    op.drop_index(op.f("ix_teams_league"), table_name="teams")
    op.drop_index(op.f("ix_teams_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_fetch_runs_league"), table_name="fetch_runs")
    op.drop_table("fetch_runs")
    # ### end Alembic commands ###
